# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('tamanho', models.CharField(max_length=5)),
                ('cor', models.CharField(max_length=120)),
                ('tipo_item', models.SmallIntegerField()),
                ('descricaocompleta', models.TextField()),
                ('codigobarras', models.CharField(max_length=100)),
                ('validadedt', models.DateField()),
                ('qtdeminima', models.IntegerField()),
                ('qtdeideal', models.IntegerField()),
                ('duracaoh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentodt', models.DateField()),
                ('tipomovimento', models.SmallIntegerField()),
                ('qtdemovimento', models.IntegerField()),
                ('valormovimento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valorunitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valorsubtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prdesconto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valordesconto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valorliquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valorimpostosdebito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valorimpostoscredito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('validadedt', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('validadedt', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopessoa', models.SmallIntegerField()),
                ('doccpfcnpj', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=120)),
                ('nomefantasia', models.CharField(max_length=120)),
                ('docrg', models.CharField(max_length=20)),
                ('docpispasep', models.CharField(max_length=20)),
                ('docinscestadual', models.CharField(max_length=20)),
                ('docinscmunicipal', models.CharField(max_length=20)),
                ('criacaodt', models.DateField()),
                ('encerramentodt', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('validadedt', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemmov',
            name='local_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Local'),
        ),
        migrations.AddField(
            model_name='itemmov',
            name='pessoa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AddField(
            model_name='item',
            name='marca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Unidade'),
        ),
    ]
