# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20160815_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmov',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigobarras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='duracaoh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='qtdeideal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='qtdeminima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='validadedt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='validadedt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='validadedt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='docinscestadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='docinscmunicipal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='docpispasep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='docrg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='encerramentodt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='validadedt',
            field=models.DateField(null=True),
        ),
    ]
