# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160820_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='local',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='user',
        ),
    ]
